server:
  port: 7010

spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:mysql://localhost:3306/WALLET-DB
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          format_sql: true
    show-sql: true

  graphql:
    graphiql:
      enabled: true